// app/layout.js or app/layout.tsx (for App Router in Next.js 13+)
import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // choose the weights you need
  display: 'swap',
  variable: '--font-poppins' // Optional: for CSS variable
});

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>{children}</body>
    </html>
  );
}
